### PR TITLE
Add tabular fork

### PR DESCRIPTION
**Pull request by harryadel**
Adding an active fork of tabular
https://github.com/d3k4y/meteor-tabular#installation

### CODE REVIEW

**Comment by arggh** [comment]
Thanks for the addition. The description for the added package could be improved though. Other packages' description tells the repo viewer immediately what the package is about, so maybe this could be "Reactive datatables for large or small datasets" - picked straight from linked repo itself?

**Comment by harryadel** [comment]
I don't mind such change but how do we indicate that it's a fork? Or it's not important to mention?

**Comment by arggh** [comment]
I don't think it's necessary to mention that it's a fork, since the original project is clearly abandoned. Likewise, we don't describe `ostrio:flow-router-extra` as a fork of `kadira:flow-router` in the list, but as a router.

Thanks for the PR!

**Comment by arggh** [comment]
I changed the package name from `aldeed:tabular` to `d3k4y:tabular`, which was the linked package.

**Comment by harryadel** [comment]
Ah, I see, thanks!

**Pull request merged**
